services:

    php-fpm:
        container_name: "${COMPOSE_PROJECT_NAME}-php-fpm"
        build:
            args:
                user: aaron
                uid: 1000
            context: docker/php-fpm
            tags: # required for Docker buildx/bake to tag properly
                - "${COMPOSE_PROJECT_NAME}-php-fpm"
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            - mysql
        environment:
            PHP_IDE_CONFIG: "serverName=${DOCKER_SERVER_NAME}"
        restart: unless-stopped

    nginx:
        container_name: "${COMPOSE_PROJECT_NAME}-nginx"
        image: nginx:1.28.0-alpine3.21
        ports:
            - "80:80"
            - "443:443"
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        restart: unless-stopped

    mysql:
        container_name: "${COMPOSE_PROJECT_NAME}-mysql"
        image: mysql:8.0.37
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        restart: unless-stopped

    node:
        container_name: "${COMPOSE_PROJECT_NAME}-node"
        build:
            context: docker/node
        working_dir: /app
        init: true
        volumes:
            - .:/app

    redis:
        container_name: "${COMPOSE_PROJECT_NAME}-redis"
        image: redis:7.2.5-alpine3.20
        restart: unless-stopped

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        restart: unless-stopped

volumes:
    mysql-data:

networks:
    default:
